# Generated by Django 4.2.26 on 2025-11-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitemmodel_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='updated_date',
        ),
    ]
