# Generated by Django 4.2.26 on 2025-11-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='berif_description',
            new_name='brief_description',
        ),
    ]
