# Generated by Django 4.2.26 on 2025-11-30 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_couponmodel_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmodel',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='useraddressmodel',
            name='update_date',
        ),
        migrations.AddField(
            model_name='couponmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
